In [ ]:
#Array --> a one dimensional container for elements that are all of the same data type
#Matrix --> a Two dimensional container for elements that are stored in an array


In [2]:
#using numpy to pperform arithematic operations on data
import numpy as np
from numpy.random import randn

In [3]:
np.set_printoptions(precision=2)

In [5]:
#create an array
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
b = np.array([[10, 20, 30], [40, 50, 60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
#create an array via assignment
np.random.seed(25)
c = 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [9]:
d = np.arange(1, 35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [10]:
#multiplying matrices and basic liner algebra
a*10

array([10, 20, 30, 40, 50, 60])

In [11]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [12]:
c-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [ ]:
#Descriptive statistics that describe the values of observations in a variable
#Descrptive statistics that describes a variable's spread

In [ ]:
#Uses of Descriptive Statistics
#--> Detecting outliers
#--> Planning data preparation requirements for data preprocessing
#--> Selecting features for use in machine learning

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

import scipy
from scipy import stats

In [2]:
address = 'cars.csv'
cars = pd.read_csv(address)
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars.head()

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [3]:
#Looking at Summery statistics that describe a variable's numeric values
cars.sum()

car_names    Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...
mpg                                                      642.9
cyl                                                        198
disp                                                    7383.1
hp                                                        4694
drat                                                    115.09
wt                                                     102.952
qsec                                                    571.16
vs                                                          14
am                                                          13
gear                                                       118
carb                                                        90
dtype: object

In [5]:
cars.sum(axis=1, numeric_only=True).head()

0    328.980
1    329.795
2    259.580
3    426.135
4    590.310
dtype: float64

In [6]:
cars.median(numeric_only=True)

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [7]:
cars.mean(numeric_only=True)

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [8]:
cars.max()

car_names    Volvo 142E
mpg                33.9
cyl                   8
disp              472.0
hp                  335
drat               4.93
wt                5.424
qsec               22.9
vs                    1
am                    1
gear                  5
carb                  8
dtype: object

In [9]:
mpg = cars.mpg
mpg.idxmax()

19

In [10]:
#Summery statistics that describe variable distribution
cars.std(numeric_only=True)

mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

In [11]:
cars.var(numeric_only=True)

mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64

In [ ]:
gear = cars.gear
gear.value_count