In [ ]:
#Array --> a one dimensional container for elements that are all of the same data type
#Matrix --> a Two dimensional container for elements that are stored in an array


In [2]:
#using numpy to pperform arithematic operations on data
import numpy as np
from numpy.random import randn

In [3]:
np.set_printoptions(precision=2)

In [5]:
#create an array
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
b = np.array([[10, 20, 30], [40, 50, 60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
#create an array via assignment
np.random.seed(25)
c = 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [9]:
d = np.arange(1, 35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [10]:
#multiplying matrices and basic liner algebra
a*10

array([10, 20, 30, 40, 50, 60])

In [11]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [12]:
c-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])