In [ ]:
#Array --> a one dimensional container for elements that are all of the same data type
#Matrix --> a Two dimensional container for elements that are stored in an array


In [2]:
#using numpy to pperform arithematic operations on data
import numpy as np
from numpy.random import randn

In [3]:
np.set_printoptions(precision=2)

In [5]:
#create an array
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
b = np.array([[10, 20, 30], [40, 50, 60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
#create an array via assignment
np.random.seed(25)
c = 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [9]:
d = np.arange(1, 35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [10]:
#multiplying matrices and basic liner algebra
a*10

array([10, 20, 30, 40, 50, 60])

In [11]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [12]:
c-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [ ]:
#Descriptive statistics that describe the values of observations in a variable
#Descrptive statistics that describes a variable's spread

In [ ]:
#Uses of Descriptive Statistics
#--> Detecting outliers
#--> Planning data preparation requirements for data preprocessing
#--> Selecting features for use in machine learning

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

import scipy
from scipy import stats

In [2]:
address = 'cars.csv'
cars = pd.read_csv(address)
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars.head()

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [3]:
#Looking at Summery statistics that describe a variable's numeric values
cars.sum()

car_names    Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...
mpg                                                      642.9
cyl                                                        198
disp                                                    7383.1
hp                                                        4694
drat                                                    115.09
wt                                                     102.952
qsec                                                    571.16
vs                                                          14
am                                                          13
gear                                                       118
carb                                                        90
dtype: object

In [5]:
cars.sum(axis=1, numeric_only=True).head()

0    328.980
1    329.795
2    259.580
3    426.135
4    590.310
dtype: float64

In [6]:
cars.median(numeric_only=True)

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [7]:
cars.mean(numeric_only=True)

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [8]:
cars.max()

car_names    Volvo 142E
mpg                33.9
cyl                   8
disp              472.0
hp                  335
drat               4.93
wt                5.424
qsec               22.9
vs                    1
am                    1
gear                  5
carb                  8
dtype: object

In [9]:
mpg = cars.mpg
mpg.idxmax()

19

In [10]:
#Summery statistics that describe variable distribution
cars.std(numeric_only=True)

mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

In [11]:
cars.var(numeric_only=True)

mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64

In [12]:
gear = cars.gear
gear.value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [13]:
cars.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [ ]:
#Categorical Variables
#--> Accept only a limited and fixed number of values
#--> Each observation is assigned to a specific subgroup


In [ ]:
#Basic ways to describe Categorical variables
#--> counts
#--> Variable Description
#--> Grouping


In [3]:
address = 'cars.csv'
cars = pd.read_csv(address)
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars.index = cars.car_names

cars.head(15)

car_names   mpg  cyl   disp   hp  drat     wt  \
car_names                                                                    
Mazda RX4                    Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag            Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                  Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive          Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout    Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   
Valiant                        Valiant  18.1    6  225.0  105  2.76  3.460   
Duster 360                  Duster 360  14.3    8  360.0  245  3.21  3.570   
Merc 240D                    Merc 240D  24.4    4  146.7   62  3.69  3.190   
Merc 230                      Merc 230  22.8    4  140.8   95  3.92  3.150   
Merc 280                      Merc 280  19.2    6  167.6  123  3.92  3.440   
Merc 280C                    Merc 280C  17.8    6  167.6  123  3.92  3.440   
Merc 450SE                  Merc 450SE  16.4    8  275.8  180  3.07  4.070   
Merc 450SL                  Merc 450SL  17.3    8  275.8  180  3.07  3.730   
Merc 450SLC                Merc 450SLC  15.2    8  275.8  180  3.07  3.780   
Cadillac Fleetwood  Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250   

                     qsec  vs  am  gear  carb  
car_names                                      
Mazda RX4           16.46   0   1     4     4  
Mazda RX4 Wag       17.02   0   1     4     4  
Datsun 710          18.61   1   1     4     1  
Hornet 4 Drive      19.44   1   0     3     1  
Hornet Sportabout   17.02   0   0     3     2  
Valiant             20.22   1   0     3     1  
Duster 360          15.84   0   0     3     4  
Merc 240D           20.00   1   0     4     2  
Merc 230            22.90   1   0     4     2  
Merc 280            18.30   1   0     4     4  
Merc 280C           18.90   1   0     4     4  
Merc 450SE          17.40   0   0     3     3  
Merc 450SL          17.60   0   0     3     3  
Merc 450SLC         18.00   0   0     3     3  
Cadillac Fleetwood  17.98   0   0     3     4

In [4]:
carb = cars.carb
carb.value_counts()

carb
4    10
2    10
1     7
3     3
6     1
8     1
Name: count, dtype: int64

In [6]:
cars_cat = cars[['cyl', 'vs', 'am', 'gear', 'carb']]
cars_cat.head()

cyl  vs  am  gear  carb
car_names                                 
Mazda RX4            6   0   1     4     4
Mazda RX4 Wag        6   0   1     4     4
Datsun 710           4   1   1     4     1
Hornet 4 Drive       6   1   0     3     1
Hornet Sportabout    8   0   0     3     2

In [7]:
gear_group = cars_cat.groupby('gear')
gear_group.describe()

cyl                                                 vs            ...  \
     count      mean       std  min  25%  50%  75%  max count      mean  ...   
gear                                                                     ...   
3     15.0  7.466667  1.187234  4.0  8.0  8.0  8.0  8.0  15.0  0.200000  ...   
4     12.0  4.666667  0.984732  4.0  4.0  4.0  6.0  6.0  12.0  0.833333  ...   
5      5.0  6.000000  2.000000  4.0  4.0  6.0  8.0  8.0   5.0  0.200000  ...   

       am       carb                                               
      75%  max count      mean       std  min  25%  50%  75%  max  
gear                                                               
3     0.0  0.0  15.0  2.666667  1.175139  1.0  2.0  3.0  4.0  4.0  
4     1.0  1.0  12.0  2.333333  1.302678  1.0  1.0  2.0  4.0  4.0  
5     1.0  1.0   5.0  4.400000  2.607681  2.0  2.0  4.0  6.0  8.0  

[3 rows x 32 columns]

In [9]:
#Transforming variables to categorical data type
cars['group'] = pd.Series(cars.gear, dtype='category')

In [10]:
cars['group'].dtypes

CategoricalDtype(categories=[3, 4, 5], ordered=False, categories_dtype=int64)

In [11]:
cars['group'].value_counts()

group
3    15
4    12
5     5
Name: count, dtype: int64

In [12]:
#Describe categorical data with crosstabs
pd.crosstab(cars['am'], cars['gear'])

gear   3  4  5
am            
0     15  4  0
1      0  8  5

In [ ]:
#Parametric Correlation Analysis
#A method for finding correlation between linearly related continuous numeric variables

In [ ]:
#pearson correlation coefficient
#R=1 Strong positive relationship
#R=0 not linearly correlated
#R=-1 Strong negative relationship


In [ ]:
#Pearson Correlation Assumptions
#--> your data is normally distributed
#--> you have continous, numeric variables
#--> your variables are linearly related

In [ ]:
#Use pearson correlation
#--> To uncover (linear) relationships between variables
#--> Not to rule out possible(nonlinear) relationships between variables

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from pylab import rcParams

import scipy
from scipy.stats import pearsonr

In [3]:
%matplotlib inline
rcParams['figure.figsize'] = 8, 4
sns.set_style("whitegrid")

In [5]:
address = 'cars.csv'
cars = pd.read_csv(address)
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

In [ ]:
sns.pairplot(cars)